### ISSUE TITLE
Task: Resource Browser refactoring & multiple fixes

### ISSUE THREAD

**Issue by Elessar1802** [devtron-labs/dashboard#1755]
The scope of this task is to refactoring the area surrounding Resource Browser. Additionally will shift the Resource Browser folder into Pages directory. It will also carry multiple fixes (UI & Functional).

**TODO**
- [ ] Refactor Resource Filtering Button/Modal in fe-lib
- [x] Deploy the changed code onto a cluster

**Comment by Elessar1802** [comment]
**Fixes done -**
- [x] Pagination breaks on search in resource browser K8sResourceTab
- [x] App Details view react select z-index
- [x] Double separators in dynamic tabs (UI bug)
- [x] Cluster Overview (dc__overflow) added to the tiles so that it doesn't break on smaller screens
- [x] Using registerShortcut from fe-common-lib

**Refactorings** -
- [x] reduced explicit useStates from 33 to 3 in ResourceList.tsx
- [x] Reduced useEffects from 10 to 3
- [x] Removed url based logic (using useEffect) to dictate dynamic tabs selection to user interaction based since it was too convoluted and incorrect
- [x] Broke down ResourceList.tsx into 2 new files - K8sResourceTabComponent.tsx and AdminTerminalComponent.tsx **Impact**: This has significantly reduced the LOC in each file leading to reduced cognitive load on the developer and also reduced prop drilling significantly. Also lead to **nice :)** separation of concern
